### ISSUE TITLE
Setting up

### ISSUE THREAD

**Issue by dymank** [sheltonial/wallaby-ng-html2js-preprocessor#1]
Hi,

I'm trying to use this preprocessor in unit tests in a project I'm working on. I don't know what is and where look for `package.json` to add devDependency, but I ran this `npm install wallaby-ng-html2js-preprocessor --save-dev` command in cmd, and something happend, but not much. It printed line:
`wallaby-ng-html2js-preprocessor@0.1.0 node_modules\wallaby-ng-html2js-preprocessor`
I have also `wallaby.conf.js` based on example in project.
When I try to start Wallaby it fails with error:
`Failed to load configuration file:  Error: Cannot find module 'wallaby-ng-html2js-preprocessor'`.

Could you please give me any advice what is wrong or what I am missing?

**Comment by ArtemGovorov** [comment]
A package.json file contains meta data about your application, it also includes the list of dependencies to install from npm when running `npm install`. You may create one if you run `npm init` in your project dir. 

When you run `npm install wallaby-ng-html2js-preprocessor --save-dev`, make sure you are in your project dir, if not `cd c:\path\to\your\project` first. After running the command, `node_modules` folder with `wallaby-ng-html2js-preprocessor` module in it will be created (if you didn't have one already).

**Comment by dymank** [comment]
Thanks a lot, it helped, but I still have some problems. 

When in conf I add all htmls with `"**/*.html"` Wallaby dosn't start and prints error:

`TypeError: Cannot read property '_session' of null
  at Server.handler (C:\Users\Agnieszka\.wallaby\core\node_modules\phantom\node_modules\shoe\index.js:10:33)
  at emitOne (events.js:77:13)
  at Server.emit (events.js:166:7)
  at App.emit (C:\Users\Agnieszka\.wallaby\core\node_modules\phantom\node_modules\shoe\node_modules\sockjs\lib\sockjs.js:182:27)
  at Session.emit_open (C:\Users\Agnieszka\.wallaby\core\node_modules\phantom\node_modules\shoe\node_modules\sockjs\lib\transport.js:107:23)
  at process._tickCallback (node.js:340:13)`

And then is quite long stack trace but starts with

`Failed to execute start operation, Error: Failed to run preprocessors on pages/cases/caseEdit.html, ReferenceError: cacheId is not defined`.

I tried loading all htmls few times and noticed that every time html from error was different.

When in conf I add only one specific html which is used in templateUrl in directive which I'm testing, Wallaby starts, but every test fail with 

`Error: [$injector:nomod] Module 'templates' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.`

to load htmls I'm using `beforeEach(module('templates'));` (and of course in conf moduleName is set to `templates`.

**Comment by ArtemGovorov** [comment]
Could you please create a small Github repository demonstrating the issue? I'll have a look what's wrong.

**Comment by ArtemGovorov** [comment]
You may also have a look into these couple of projects where `wallaby-ng-html2js-preprocessor` is used to load templates:
https://github.com/ONE-LOGIC/ngFlowchart/blob/master/wallaby.js
https://github.com/xebia/angular-form-messages/blob/master/wallaby.conf.js

**Comment by dymank** [comment]
Is this even possible to run this without Karma?
I'm using Visual Studio and Chutzpah. Everything was fine untill I have started testing directives with htmls in external files loaded in templateUrl.

**Comment by ArtemGovorov** [comment]
Could you please create a small Github repository demonstrating the issue? We'll figure it out.

**Comment by dymank** [comment]
I have created small repo which reproduces my issue: https://github.com/aanklewicz92/wallabytest.

**Comment by ArtemGovorov** [comment]
Thanks for the repo. The issue is that `*.html` files are not included in the `files` list. 

``` JavaScript
        files: [
            "src/jquery-1.10.2.min.js",
            "src/angular.js",
            "src/angular-mocks.js",
            "src/app.js",
            "src/procedures.js",
            "src/statisticOptions.js",
            "src/**/*.html"  // all used files need to be included
        ],
```

After I include `src/**/*.html`, the templates start to load. The tests are still failing, but for some other, not templates related, reasons.

Also, by default wallaby instruments all files in the `files` list. I'd recommend [setting `instrument` flag to `false`](http://wallabyjs.com/docs/config/files.html#file-object) for libraries. Since you probably don't need the code coverage for the libraries, it'll allow wallaby to run your tests even faster:

``` JavaScript
        files: [
            {pattern: "src/jquery-1.10.2.min.js", instrument: false},
            {pattern: "src/angular.js", instrument: false},
            {pattern: "src/angular-mocks.js", instrument: false},
            "src/app.js",
            "src/procedures.js",
            "src/statisticOptions.js",
            "src/**/*.html"
        ],
```

**Comment by dymank** [comment]
What is your reason of failures of tests after including `src/**/*.html`?

**Comment by ArtemGovorov** [comment]
@aanklewicz92 I'm not an expert in angular.js, but wallaby reports `TypeError: 'undefined' is not an object (evaluating 'a.isolateScope().vm')` and trying to `console.log(a.isolateScope())` gives `undefined`. Maybe it's [this issue](http://stackoverflow.com/questions/21578762/isolatescope-returns-undefined-when-using-templateurl), maybe not, but definitely not a wallaby.js issue.

**Comment by dymank** [comment]
Thanks, just wanted to be sure that you have the same error. I think I can close that issue since it's not problem with Wallaby or preprocessor. Thank you for all your help.

**Comment by ArtemGovorov** [comment]
@aanklewicz92 Awesome, thanks. If you have any other issues with/questions about configuring and using wallaby, please feel free to create issues in [our public repo](https://github.com/wallabyjs/public/issues).
